//! Each architecture defines a set of constants in #defines. These
//! constants describe the memory regions of the kernel's portion of the
//! address space including the physical memory window, the kernel ELF
//! region, and the device region.
//!
//!  - USER_TOP: The first address after the end of user memory
//!
//!  - PADDR_BASE: The first physical address mapped in the kernel's
//!    physical memory window.
//!  - PPTR_BASE: The first virtual address of the kernel's physical
//!    memory window.
//!  - PPTR_TOP: The first virtual address after the end of the kernel's
//!    physical memory window.
//!
//!  - KERNEL_ELF_PADDR_BASE: The first physical address used to map the
//!    initial kernel image. The kernel ELF is mapped contiguously
//!    starting at this address.
//!  - KERNEL_ELF_BASE: The first virtual address used to map the initial
//!    kernel image.
//!
//!  - KDEV_BASE: The first virtual address used to map devices.

/// The offset from a physical address to a virtual address in the
/// physical memory window.
use core::ffi::c_void;
use crate::arch::hardware::{KERNEL_ELF_BASE, KERNEL_ELF_PADDR_BASE, PADDR_BASE, PPTR_BASE, PPTR_TOP};

pub const PPTR_BASE_OFFSET: usize = PPTR_BASE - PADDR_BASE;

/// The last address in the physical memory region mapped into the
/// physical memory window
pub const PADDR_TOP: usize = PPTR_TOP - PPTR_BASE_OFFSET;

/// The kernel base offset is a way to translate the kernel image segment
/// from virtual to physical. This translation must be a single offset
/// for for the entire segment (i.e. the kernel image must be contiguous
/// both virtually and physically)
pub const KERNEL_ELF_BASE_OFFSET: usize = KERNEL_ELF_BASE - KERNEL_ELF_PADDR_BASE;

/* This symbol is generated by the linker and marks the last valid
 * address in the kernel's virtual region */
unsafe extern "C" {
    // Its defined as a byte because we don't actually care about the value here. Just the
    // pointer.
    static ki_end: [u8; 1];
}

/// This value marks the last valid address in the kernel's virtual region.
/// Note this is a pointer because the value unfortunately isn't known at compile time.
pub const KERNEL_ELF_TOP: *const u8 = unsafe { ki_end.as_ptr() };
